modLoader="javafml"
loaderVersion="[32,)"
logoFile=""
authors=""
credits=""

[[mods]]
    modId="flora_resourca"
    version="${file.jarVersion}"
    displayName="Flora Resourca"
    description='''
Stuff'''

[[dependencies.flora_resourca]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.72,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.flora_resourca]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"